# Generated by Django 4.1.13 on 2024-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_markers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marker',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
